--DROPAR O DATABASE
USE master
IF EXISTS(SELECT * FROM sys.databases WHERE name='ATENTO')
	DROP DATABASE ATENTO

--CRIAR O DATABASE
CREATE DATABASE ATENTO
--F5 = EXECUTA O COMANDO SELECIONADO OU TODOS OS COMANDOS
--CTRL+SHIFT+U - CONVERTE PARA MAIÚSCULAS
--CTRL+R - RESULT PANEL
--CTRL+S - SALVA O ARQUIVO

--FORÇA A EXECUÇÃO DO SCRIPT ATÉ ESSE PONTO
GO

--ACESSAR O DATABASE 
USE ATENTO

/*
	COMO O SQL SERVER EXECUTA UM COMANDO QUALQUER:
	
	- PARSE - VERIFICAR A SINTAXE DO COMANDO 
	          E EXISTÊNCIA DOS OBJETOS
	- ANÁLISE - DETERMINAR O MELHOR CAMINHO PARA ACESSAR
	            OS DADOS
	- EXECUÇÃO - CUMPRIMENTO DO PLANO DE EXECUÇÃO
*/

--CRIAR TABELA
CREATE TABLE PESSOA --Pessoa
(
	PESSOA_CODIGO INT, --PessoaId
	PESSOA_NOME VARCHAR(50), --PessoaNome
	PESSOA_SEXO CHAR(1) --PessoaSexo
)

--DROPAR A TABELA
IF EXISTS(SELECT * FROM sys.objects WHERE name = 'PESSOA')
	DROP TABLE PESSOA

CREATE TABLE PESSOA
(
	PESSOA_CODIGO INT NOT NULL IDENTITY/*(1, 1)*/, 
	PESSOA_NOME VARCHAR(50) NOT NULL, 
	PESSOA_SEXO CHAR(1) 
)

--EXEMPLO DE SINTAXE COMPLETA

--CREATE DATABASE [ATENTO];

--CREATE TABLE [dbo].[PESSOA](
--	[PESSOA_CODIGO] [int] IDENTITY(1,1) NOT NULL,
--	[PESSOA_NOME] [varchar](50) NOT NULL,
--	[PESSOA_SEXO] [char](1) NULL
--) ON [GRUPO];

INSERT PESSOA 
VALUES('ADÃO', 'M'), 
	('EVA', 'F'), 
	('CAIM', 'M'), 
	('ABEL', 'M')

--2005
--INSERT PESSOA VALUES('ADÃO', 'M') 
--INSERT PESSOA VALUES('EVA', 'F')
--INSERT PESSOA VALUES('CAIM', 'M') 
--INSERT PESSOA VALUES('ABEL', 'M')

--7
--INSERT INTO PESSOA VALUES('ADÃO', 'M') 
--INSERT INTO PESSOA VALUES('EVA', 'F')
--INSERT INTO PESSOA VALUES('CAIM', 'M') 
--INSERT INTO PESSOA VALUES('ABEL', 'M')

--SHIFT+ALT+ENTER - TELA CHEIA

--OBTER OS DADOS DA TABELA
SELECT *
FROM PESSOA

--CTRL+D - RESULTSET COMO DADOS (GRID)
--CTRL+T - RESULTSET COMO TEXTO

SELECT PESSOA_CODIGO, 
	PESSOA_NOME, 
	PESSOA_SEXO
FROM PESSOA

UPDATE PESSOA
SET PESSOA_NOME = PESSOA_NOME + '*', 
	PESSOA_SEXO = LOWER(PESSOA_SEXO)

SELECT *
FROM PESSOA

DELETE 
/*FROM*/ PESSOA
WHERE PESSOA_CODIGO = 3

SELECT *
FROM PESSOA

INSERT /*INTO*/ PESSOA VALUES('CAIM', 'M')

SELECT *
FROM PESSOA

DELETE PESSOA

INSERT PESSOA 
VALUES ('AGNALDO', 'M')

SELECT * 
FROM PESSOA

TRUNCATE TABLE PESSOA

INSERT PESSOA 
VALUES ('AGNALDO', 'M')

SELECT * 
FROM PESSOA

DROP TABLE PESSOA

---------------------

CREATE TABLE GENERO
(
	GENERO_CODIGO INT IDENTITY, 
	GENERO_DESCRICAO VARCHAR(20)
)

CREATE TABLE ATOR
(
	ATOR_CODIGO INT IDENTITY, 
	ATOR_NOME VARCHAR(50)
)

CREATE TABLE DIRETOR
(
	DIRETOR_CODIGO INT IDENTITY,
	DIRETOR_NOME VARCHAR(50)
)

CREATE TABLE FILME
(
	FILME_CODIGO INT IDENTITY, 
	FILME_NOME_ORIGINAL VARCHAR(50),
	FILME_NOME_PT_BR VARCHAR(50),
	FILME_ANO SMALLINT	 
)

CREATE TABLE FILME_GENERO
(
	FILME_CODIGO INT,
	GENERO_CODIGO INT
)

CREATE TABLE FILME_ATOR
(
	FILME_CODIGO INT,
	ATOR_CODIGO INT
)

CREATE TABLE FILME_DIRETOR
(
	FILME_CODIGO INT,
	DIRETOR_CODIGO INT
)

-- 1:1 -> PESSOA -> CONJUGE
-- 1:N -> PEDIDO -> ITEM_PEDIDO
-- M:N -> AUTOR -> LIVRO

INSERT GENERO 
VALUES ('GUERRA'),
	('FICÇÃO'),
	('TERROR')
	
INSERT ATOR 
VALUES ('SYLVESTER STALONE'), 
	('CLINT EASTWOOD'), 
	('CHUCK NORRIS'), 
	('JET LI'), 
	('BRUCE LEE')

INSERT DIRETOR 
VALUES ('CLINT EASTWOOD'), 
	('SIMON WEST')

