USE master 

IF EXISTS(SELECT * FROM sys.databases WHERE name='ATENTO')
	DROP DATABASE ATENTO
	
CREATE DATABASE ATENTO
GO

USE ATENTO

CREATE TABLE CATEGORIA
(
	COD_CATEGORIA INT IDENTITY PRIMARY KEY, 
	DESCRICAO_CATEGORIA VARCHAR(50)
)

CREATE TABLE PRODUTO
(
	COD_PRODUTO INT IDENTITY PRIMARY KEY, 
	DESCRICAO_PRODUTO VARCHAR(50), 
	PRECO_PRODUTO DEC(9,2),
	QTD_ESTOQUE_PRODUTO INT, 
	COD_CATEGORIA INT REFERENCES CATEGORIA
)

INSERT CATEGORIA 
VALUES ('FERRAMENTAS'), 
	('MATERIAIS DE ESCRITÓRIO'), 
	('CAMA E BANHO') 

INSERT PRODUTO
VALUES ('MARTELO', 12, 100, 1), 
	('MARRETA', 19, 90, 1), 
	('GRAMPEADOR 25/5', 5, 23, 2), 
	('SERROTE', 25, 8, 1), 
	('ARCO DE SERRA', 19.54, 2, 1), 
	('BLOCO DE ANOTAÇÕES', 3.92, 1000, 2), 
	('TOALHA DE MESA 1,8M X 3,20M', 98.43, 12, NULL), 
	('FURADEIRA DE IMPACTO', 280.57, 9, 1), 
	('PARAFUSADEIRA', 50, 7, 1), 
	('AGENDA 2012', 0.51, 1234, 2), 
	('ALMOFADA PARA CARIMBO', 2.5, 21, 2)

SELECT *
FROM CATEGORIA

SELECT * 
FROM PRODUTO

SELECT COD_CATEGORIA, 
	COUNT(*) AS 'QTD'
FROM PRODUTO
GROUP BY COD_CATEGORIA

SELECT C.DESCRICAO_CATEGORIA, 
	COUNT(*) AS 'QTD'
FROM PRODUTO P
LEFT JOIN CATEGORIA C ON P.COD_CATEGORIA = C.COD_CATEGORIA
GROUP BY C.DESCRICAO_CATEGORIA

SELECT *, 
	(
		SELECT COUNT(*) 
		FROM PRODUTO P 
		WHERE P.COD_CATEGORIA = C.COD_CATEGORIA
	) AS 'QTD_PRODUTOS'
FROM CATEGORIA C

SELECT C.*
FROM CATEGORIA C
LEFT JOIN PRODUTO P ON P.COD_CATEGORIA = C.COD_CATEGORIA
WHERE P.COD_PRODUTO IS NULL

SELECT *
FROM CATEGORIA 
WHERE COD_CATEGORIA NOT IN 
	(
		SELECT COD_CATEGORIA 
		FROM PRODUTO
		WHERE COD_CATEGORIA IS NOT NULL
	)

SELECT DISTINCT C.*
FROM CATEGORIA C
INNER JOIN PRODUTO P ON P.COD_CATEGORIA = C.COD_CATEGORIA
WHERE P.QTD_ESTOQUE_PRODUTO = 1000

SELECT *
FROM CATEGORIA C
WHERE COD_CATEGORIA IN 
	(
		SELECT COD_CATEGORIA 
		FROM PRODUTO P
		WHERE C.COD_CATEGORIA = P.COD_CATEGORIA 
			AND P.QTD_ESTOQUE_PRODUTO = 1000
	)
	
--CATEGORIA (*), MENOR PRECO, MAIOR PRECO, MEDIA PRECO, QTD 
SELECT C.COD_CATEGORIA,
	C.DESCRICAO_CATEGORIA,
	MIN(P.PRECO_PRODUTO) AS 'MIN', 
	MAX(P.PRECO_PRODUTO) AS 'MAX', 
	AVG(P.PRECO_PRODUTO) AS 'AVG', 
	COUNT(P.COD_PRODUTO) AS 'QTD'
FROM CATEGORIA C
LEFT JOIN PRODUTO P ON P.COD_CATEGORIA = C.COD_CATEGORIA
GROUP BY C.COD_CATEGORIA,
	C.DESCRICAO_CATEGORIA
	
SELECT *, 
	(SELECT MIN(PRECO_PRODUTO) FROM PRODUTO P 
		WHERE C.COD_CATEGORIA = P.COD_CATEGORIA) AS 'MIN',  
	(SELECT MAX(PRECO_PRODUTO) FROM PRODUTO P 
		WHERE C.COD_CATEGORIA = P.COD_CATEGORIA) AS 'MAX',  
	(SELECT AVG(PRECO_PRODUTO) FROM PRODUTO P 
		WHERE C.COD_CATEGORIA = P.COD_CATEGORIA) AS 'AVG',  
	(SELECT COUNT(*) FROM PRODUTO P 
		WHERE C.COD_CATEGORIA = P.COD_CATEGORIA) AS 'QTD' 
FROM CATEGORIA C 

