USE master 

IF EXISTS(SELECT * FROM sys.databases WHERE name='ATENTO')
	DROP DATABASE ATENTO
	
CREATE DATABASE ATENTO
GO

USE ATENTO

CREATE TABLE PESSOA
(
	COD_PESSOA INT IDENTITY PRIMARY KEY, 
	NOME_PESSOA VARCHAR(50), 
	SEXO_PESSOA CHAR(1)
)

INSERT INTO PESSOA 
VALUES ('ADAO', 'M'), 
	('EVA', 'F'), 
	('CAIM', 'M'), 
	('ABEL', 'M')

SELECT * 
FROM PESSOA

GO

CREATE VIEW UV_PESSOA_M
AS
	SELECT *
	FROM PESSOA 
	WHERE SEXO_PESSOA = 'M'
GO

SELECT * 
FROM UV_PESSOA_M

EXEC sp_help UV_PESSOA_M

EXEC sp_helptext UV_PESSOA_M

GO

ALTER VIEW UV_PESSOA_M
	WITH ENCRYPTION
AS
	SELECT *
	FROM PESSOA 
	WHERE SEXO_PESSOA = 'M'
GO

SELECT * 
FROM UV_PESSOA_M

EXEC sp_help UV_PESSOA_M

EXEC sp_helptext UV_PESSOA_M

GO

ALTER VIEW UV_PESSOA_M
--	WITH ENCRYPTION
AS
	SELECT *
	FROM PESSOA 
	WHERE SEXO_PESSOA = 'M'
GO

EXEC sp_helptext UV_PESSOA_M

SELECT * 
FROM UV_PESSOA_M
ORDER BY NOME_PESSOA

INSERT UV_PESSOA_M
VALUES ('COBRA', NULL)

SELECT * 
FROM UV_PESSOA_M

SELECT *
FROM PESSOA

CREATE TABLE CATEGORIA
(
	COD_CATEGORIA INT IDENTITY PRIMARY KEY, 
	DESCRICAO_CATEGORIA VARCHAR(50)
)

CREATE TABLE PRODUTO
(
	COD_PRODUTO INT IDENTITY PRIMARY KEY, 
	DESCRICAO_PRODUTO VARCHAR(50), 
	PRECO_PRODUTO DEC(9,2),
	QTD_ESTOQUE_PRODUTO INT, 
	COD_CATEGORIA INT REFERENCES CATEGORIA
)

INSERT CATEGORIA 
VALUES ('FERRAMENTAS'), 
	('MATERIAIS DE ESCRITÓRIO'), 
	('CAMA E BANHO') 

INSERT PRODUTO
VALUES ('MARTELO', 12, 0, 1), 
	('MARRETA', 19, 0, 1), 
	('GRAMPEADOR 25/5', 5, 23, 2), 
	('SERROTE', 25, 8, 1), 
	('ARCO DE SERRA', 19.54, 2, 1), 
	('BLOCO DE ANOTAÇÕES', 3.92, 1000, 2), 
	('TOALHA DE MESA 1,8M X 3,20M', 98.43, 12, NULL), 
	('FURADEIRA DE IMPACTO', 280.57, 9, 1), 
	('PARAFUSADEIRA', 50, 7, 1), 
	('AGENDA 2012', 0.51, 1234, 2), 
	('ALMOFADA PARA CARIMBO', 2.5, 21, NULL)

GO

CREATE VIEW UV_CATEGORIA_SEM_PRODUTO
AS
	SELECT C.*
	FROM CATEGORIA C
	LEFT JOIN PRODUTO P ON C.COD_CATEGORIA = P.COD_CATEGORIA
	WHERE P.COD_PRODUTO IS NULL
GO

SELECT * 
FROM UV_CATEGORIA_SEM_PRODUTO

GO

CREATE VIEW UV_CATEGORIA_PRODUTO
AS
	SELECT C.*, 
		P.COD_PRODUTO, 
		P.DESCRICAO_PRODUTO, 
		P.PRECO_PRODUTO, 
		P.QTD_ESTOQUE_PRODUTO
	FROM CATEGORIA C
	JOIN PRODUTO P ON C.COD_CATEGORIA = P.COD_CATEGORIA
GO

SELECT *
FROM UV_CATEGORIA_PRODUTO

