USE master 

IF EXISTS(SELECT * FROM sys.databases WHERE name='ATENTO')
	DROP DATABASE ATENTO
	
CREATE DATABASE ATENTO
GO

USE ATENTO

CREATE TABLE PESSOA
(
	COD_PESSOA INT IDENTITY PRIMARY KEY, 
	NOME_PESSOA VARCHAR(50), 
	SEXO_PESSOA CHAR(1)
)

INSERT INTO PESSOA 
VALUES ('ADAO', 'M'), 
	('EVA', 'F'), 
	('CAIM', 'M'), 
	('ABEL', 'M')

SELECT * 
FROM PESSOA

INSERT PESSOA
VALUES ('COBRA', NULL)

SELECT COD_PESSOA,
	NOME_PESSOA, 
	CASE SEXO_PESSOA
		WHEN 'M' THEN 'MASCULINO' 
		WHEN 'F' THEN 'FEMININO' 
		ELSE 'NAO INFORMADO'
	END AS SEXO_PESSOA
FROM PESSOA

GO

CREATE FUNCTION UFN_SEXO
(
	@LETRA CHAR(1) --ARGUMENTO DA FUNCAO
)
RETURNS VARCHAR(15)
AS
BEGIN
	DECLARE @RETORNO VARCHAR(15) = 'NAO INFORMADO'
	
	IF(@LETRA = 'M')
		SET @RETORNO = 'MASCULINO'

	IF(@LETRA = 'F')
		SET @RETORNO = 'FEMININO'

	RETURN @RETORNO;
END
GO

SELECT COD_PESSOA, 
	NOME_PESSOA, 
	dbo.UFN_SEXO(SEXO_PESSOA) AS SEXO_PESSOA
FROM PESSOA

