USE master 

IF EXISTS(SELECT * FROM sys.databases WHERE name='ATENTO')
	DROP DATABASE ATENTO
	
CREATE DATABASE ATENTO
GO

USE ATENTO

CREATE TABLE PESSOA
(
	COD_PESSOA INT IDENTITY PRIMARY KEY, 
	NOME_PESSOA VARCHAR(50), 
	SEXO_PESSOA CHAR(1)
)

INSERT INTO PESSOA 
VALUES ('ADAO', 'M'), 
	('EVA', 'F'), 
	('CAIM', 'M'), 
	('ABEL', 'M')

SELECT * 
FROM PESSOA

INSERT PESSOA
VALUES ('COBRA', NULL)

SELECT COD_PESSOA,
	NOME_PESSOA, 
	CASE SEXO_PESSOA
		WHEN 'M' THEN 'MASCULINO' 
		WHEN 'F' THEN 'FEMININO' 
		ELSE 'NAO INFORMADO'
	END AS SEXO_PESSOA
FROM PESSOA

GO

CREATE FUNCTION UFN_SEXO
(
	@LETRA CHAR(1) --ARGUMENTO DA FUNCAO
)
RETURNS VARCHAR(15)
AS
BEGIN
	DECLARE @RETORNO VARCHAR(15) = 'NAO INFORMADO'
	
	IF(@LETRA = 'M')
		SET @RETORNO = 'MASCULINO'

	IF(@LETRA = 'F')
		SET @RETORNO = 'FEMININO'

	RETURN @RETORNO;
END
GO

SELECT COD_PESSOA, 
	NOME_PESSOA, 
	dbo.UFN_SEXO(SEXO_PESSOA) AS SEXO_PESSOA
FROM PESSOA

GO

CREATE FUNCTION UFN_SOMAR
(
	@X INT, 
	@Y INT
)
RETURNS INT
AS
BEGIN
	RETURN @X+@Y
END
GO

SELECT dbo.UFN_SOMAR(1,2)

CREATE TABLE PRODUTO
(
	COD_PRODUTO INT IDENTITY PRIMARY KEY,
	NOME_PRODUTO VARCHAR(50), 
	PRECO_DOLAR_PRODUTO MONEY
)

INSERT PRODUTO 
VALUES ('MARTELO', 1.234), 
	('SERROTE', 12.2455), 
	('SERRA ELETRICA', 200), 
	('MARRETA', 0.98)

CREATE TABLE DOLAR
(
	DATA_DOLAR DATE PRIMARY KEY, 
	VALOR_DOLAR MONEY 
)

INSERT DOLAR
VALUES ('20121020', 1.9), 
	('20121021', 2.1), 
	('20121024', 2.024), 
	('20121025', 2.025)
	
GO

CREATE FUNCTION UFN_CONVERTE
(
	@VALOR MONEY, 
	@DATA_DOLAR DATE
)
RETURNS MONEY
WITH ENCRYPTION 
AS
BEGIN 
	DECLARE @VALOR_DOLAR MONEY
	
	SELECT TOP 1 @VALOR_DOLAR = VALOR_DOLAR
	FROM DOLAR
	WHERE DATA_DOLAR <= @DATA_DOLAR
	ORDER BY DATA_DOLAR DESC
	
	RETURN @VALOR_DOLAR * @VALOR
END
GO

SELECT GETDATE()

SELECT *, 
	dbo.UFN_CONVERTE(PRECO_DOLAR_PRODUTO, /*GETDATE()*/ '20121025') 
		AS 'PRECO_REAL_PRODUTO'
FROM PRODUTO
