USE master 

IF EXISTS(SELECT * FROM sys.databases WHERE name='ATENTO')
	DROP DATABASE ATENTO
	
CREATE DATABASE ATENTO
GO

USE ATENTO

CREATE TABLE PESSOA
(
	COD_PESSOA INT IDENTITY PRIMARY KEY, 
	NOME_PESSOA VARCHAR(50), 
	SEXO_PESSOA CHAR(1)
)

GO

CREATE PROC USP_PESSOA_INSERIR
	@NOME_PESSOA VARCHAR(50), 
	@SEXO_PESSOA CHAR(1)
AS
	INSERT PESSOA
	VALUES (@NOME_PESSOA, @SEXO_PESSOA)
GO

EXEC USP_PESSOA_INSERIR 'ADAO', 'M'
EXEC USP_PESSOA_INSERIR 'EVA', 'F'
EXEC USP_PESSOA_INSERIR 'CAIM', 'M'
EXEC USP_PESSOA_INSERIR 'ABEL', 'M'

SELECT * FROM PESSOA

GO

CREATE PROC USP_PESSOA_UPDATE
	@COD_PESSOA INT, 
	@NOME_PESSOA VARCHAR(50), 
	@SEXO_PESSOA CHAR(1)
AS
	UPDATE PESSOA
	SET NOME_PESSOA = @NOME_PESSOA, 
		SEXO_PESSOA = @SEXO_PESSOA
	WHERE COD_PESSOA = @COD_PESSOA
GO

--SERVIDOR.DATABASE.SCHEMA.OBJETO
SELECT *
FROM [NY-SQL-01].ATENTO.dbo.PESSOA

SELECT *
FROM PESSOA

SELECT *
FROM master.dbo.MSreplication_options

SELECT *
FROM master..MSreplication_options

EXEC USP_PESSOA_UPDATE 4, 'ABELARDO', 'M'

SELECT *
FROM PESSOA

GO

CREATE PROC USP_PESSOA_SELECIONAR
AS
	SELECT * 
	FROM PESSOA
GO

CREATE PROC USP_PESSOA_SELECIONAR_COD_PESSOA
	@COD_PESSOA INT
AS
	SELECT * 
	FROM PESSOA 
	WHERE COD_PESSOA = @COD_PESSOA
GO

CREATE PROC USP_PESSOA_SELECIONAR_NOME_PESSOA
	@NOME_PESSOA VARCHAR(50)
AS
	SELECT * 
	FROM PESSOA 
	WHERE NOME_PESSOA = @NOME_PESSOA
GO

EXEC USP_PESSOA_SELECIONAR 
EXEC USP_PESSOA_SELECIONAR_COD_PESSOA 1
EXEC USP_PESSOA_SELECIONAR_NOME_PESSOA 'CAIM'


