USE master 

IF EXISTS(SELECT * FROM sys.databases WHERE name='ATENTO')
	DROP DATABASE ATENTO
	
CREATE DATABASE ATENTO
GO

USE ATENTO

CREATE TABLE PESSOA
(
	COD_PESSOA INT IDENTITY PRIMARY KEY, 
	NOME_PESSOA VARCHAR(50), 
	SEXO_PESSOA CHAR(1)
)

GO

--SELECT SUSER_SNAME(), HOST_NAME(), APP_NAME(), CURRENT_USER
--SELECT GETDATE(), SYSDATETIME()

CREATE TABLE LOG
(
	DATA_LOG DATETIME2 DEFAULT SYSDATETIME(), 
	LOGIN_LOG SYSNAME DEFAULT SUSER_SNAME(), 
	USER_LOG SYSNAME DEFAULT CURRENT_USER, 
	HOST_LOG SYSNAME DEFAULT HOST_NAME(),  
	APP_LOG SYSNAME DEFAULT APP_NAME(),
	ACAO_LOG CHAR(1), --I OU U OU D
	TABELA_LOG SYSNAME, 
	DADOS_LOG VARCHAR(MAX) 
)

GO

CREATE TRIGGER UTR_PESSOA_INSERT
ON PESSOA
FOR INSERT 
AS
	--INSERTED - TABELA COM OS DADOS INSERIDOS

	INSERT LOG (ACAO_LOG, TABELA_LOG, DADOS_LOG)
	SELECT 'I', 
		'PESSOA', 
		CAST(COD_PESSOA AS VARCHAR) + 
			'|' + NOME_PESSOA + 
			'|' + SEXO_PESSOA
	FROM INSERTED
GO

INSERT PESSOA 
VALUES ('ADAO', 'M'), 
	('EVA', 'F'), 
	('CAIM', 'M'), 
	('ABEL', 'M')

SELECT * 
FROM PESSOA

SELECT * 
FROM LOG

DROP TABLE PESSOA

CREATE TABLE PESSOA
(
	COD_PESSOA UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() PRIMARY KEY, 
	NOME_PESSOA VARCHAR(50), 
	SEXO_PESSOA CHAR(1)
)

SELECT NEWID()
SELECT NEWID()
SELECT NEWID()

INSERT PESSOA 
VALUES (DEFAULT, 'ADAO', 'M'), 
	(DEFAULT, 'EVA', 'F'), 
	(DEFAULT, 'CAIM', 'M'), 
	(DEFAULT, 'ABEL', 'M')

SELECT * 
FROM PESSOA

DROP TABLE PESSOA

CREATE TABLE PESSOA
(
	COD_PESSOA CHAR(8) /*DEFAULT LEFT(NEWID(),8)*/ PRIMARY KEY, 
	NOME_PESSOA VARCHAR(50) UNIQUE, 
	SEXO_PESSOA CHAR(1)
)

GO

CREATE TRIGGER UTR_PESSOA_INSERT
ON PESSOA 
INSTEAD OF INSERT
AS
	INSERT PESSOA
	SELECT LEFT(NEWID(), 8), 
		NOME_PESSOA,
		SEXO_PESSOA
	FROM INSERTED
GO

INSERT PESSOA 
VALUES (NULL, 'ADAO', 'M'), 
	(NULL, 'EVA', 'F'), 
	(NULL, 'CAIM', 'M'), 
	(NULL, 'ABEL', 'M')

SELECT * 
FROM PESSOA